---
dependencies: []

galaxy_info:
  role_name: create_kvm
  author: Lorenzo Calisti
  description: Create and manage a Proxmox KVM.
  license: "MIT"
  min_ansible_version: "2.1"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - proxmox
    - kvm
