---
caddy_email: "{{ vault_caddy_email }}"
caddy_local_certs: true

# Static Caddy sites.
# These entries are defined explicitly and are not generated dynamically
# from the distributed `caddy_sites` variables collected across the inventory.
# They typically represent global or standalone configurations that do not
# belong to a specific service host.
caddy_sites:
  - hostname: "{{ network.domain }}"
    public: true
    www_redir: true
