---
- name: Manage system users.
  ansible.builtin.user:
    name: "{{ item.name | ansible.builtin.mandatory }}"
    uid: "{{ item.uid | default(omit) }}"
    comment: "{{ item.comment | default(omit) }}"
    group: "{{ item.group | default(omit) }}"
    groups: "{{ item.groups | default(omit) }}"
    state: "{{ item.state | default('present') }}"
    home: "{{ item.home | default(omit) }}"
    create_home: "{{ item.create_home | default(omit) }}"
    shell: "{{ item.shell | default(system_users_default_shell) }}"
    system: "{{ item.system | default(omit) }}"
    password: "{{ item.password | default(omit) }}"
    expires: "{{ item.expires | default(omit) }}"
  loop: "{{ system_users }}"
  loop_control:
    label: "{{ item.name }}"

- name: Add sudo options for users.
  ansible.builtin.template:
    src: sudoers_user.j2
    dest: "/etc/sudoers.d/users"
    mode: "{{ system_users_sudo_mode }}"
    validate: "{{ system_users_sudo_validate_cmd }}"

- name: Deploy authorized keys for users.
  ansible.posix.authorized_key:
    user: "{{ item.name | ansible.builtin.mandatory }}"
    state: present
    exclusive: true
    key: "{{ item.authorized_keys | join('\n') }}"
  when: item.authorized_keys is defined
  loop: "{{ system_users }}"
  loop_control:
    label: "{{ item.name }}"
