---
motd_remove_dynamic:
  - "/etc/update-motd.d/00-header"
  - "/etc/update-motd.d/10-help-text"
  - "/etc/update-motd.d/50-motd-news"
  - "/etc/update-motd.d/88-esm-announce"
  - "/etc/update-motd.d/91-contract-ua-esm-status"
  - "/etc/update-motd.d/91-release-upgrade"
