$ANSIBLE_VAULT;1.1;AES256
30303837616365376339373935383962666430633637373432333636666565646366653830383732
6631633730336537313361626237346664383536383033380a383564366638303762306466333132
62653437663632393932666362343363376334616531626333363964626663613039363732373938
6133653362323465360a616262393331313063663765646536653937633739616663333764383962
61653731363766353533386466386262326266653238633931643561303563376334396461373661
3832366366363664303165336639646534306232393162613939
