---
# Configure Grafana https://github.com/grafana/grafana-ansible-collection/tree/main/roles/grafana
# Grafana init from https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/
grafana_ini:
  security:
    admin_user: "{{ vault_grafana_admin_user }}"
    admin_password: "{{ vault_grafana_admin_password }}"
    admin_email: "{{ vault_grafana_admin_email }}"
    allow_embedding: false
  server:
    http_port: "{{ grafana_dashboard_port }}"
    root_path: "https://{{ grafana_dashboard_domain }}"
  users:
    allow_sign_up: false
    allow_org_create: false
    auto_assign_org_role: "Viewer"
  metrics:
    enabled: false

# Dashboards folder on controller node
grafana_dashboards_dir: "files/grafana/dashboards"

# Datasources from https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources
grafana_datasources: []

# Plugins to install from https://grafana.com/plugins
grafana_plugins: []
