---
dependencies: []

galaxy_info:
  role_name: system_update
  author: Lorenzo Calisti
  description: Update system packages on Linux.
  license: MIT
  min_ansible_version: "2.1"
  platforms:
    - name: Alpine
      versions:
        - all
    - name: ArchLinux
      versions:
        - all
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - all
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
  galaxy_tags:
    - update
    - upgrade
    - unattendedupgrades
    - automaticupdates
