---
- name: Manage system users.
  ansible.builtin.user:
    name: "{{ __user.name | ansible.builtin.mandatory }}"
    uid: "{{ __user.uid | default(omit) }}"
    comment: "{{ __user.comment | default(omit) }}"
    group: "{{ __user.group | default(omit) }}"
    groups: "{{ __user.groups | default(omit) }}"
    state: "{{ __user.state | default('present') }}"
    home: "{{ __user.home | default(omit) }}"
    create_home: "{{ __user.create_home | default(omit) }}"
    shell: "{{ __user.shell | default(system_users_default_shell) }}"
    system: "{{ __user.system | default(omit) }}"
    password: "{{ __user.password | default(omit) }}"
    expires: "{{ __user.expires | default(omit) }}"
  loop: "{{ system_users }}"
  loop_control:
    label: "{{ __user.name }}"
    loop_var: __user

- name: Add sudo options for users.
  ansible.builtin.template:
    src: sudoers_user.j2
    dest: "/etc/sudoers.d/users"
    mode: "{{ system_users_sudo_mode }}"
    validate: "{{ system_users_sudo_validate_cmd }}"

- name: Deploy authorized keys for users.
  ansible.posix.authorized_key:
    user: "{{ __user.name | ansible.builtin.mandatory }}"
    state: present
    exclusive: true
    key: "{{ __user.authorized_keys | join('\n') }}"
  when: __user.authorized_keys is defined
  loop: "{{ system_users }}"
  loop_control:
    label: "{{ __user.name }}"
    loop_var: __user
