---
# Reboot the system after updates
update_reboot: false

# Check for network connectivity before updating
update_network_check: true
update_network_dns_domains:
  - "github.com"
update_network_http_timeout: 5
update_network_http_status_codes:
  - 200
  - 204
update_network_http_urls:
  - "https://google.com/generate_204"

# Print upgradable packages
update_print_upgradable: true

# Clean old packages
update_autoremove: true

# List of additional packages to install
update_install_packages: []

# Upgrade type used by APT
update_apt_upgrade_type: "safe"

# Configure automatic updates on Debian and RedHat
update_autoupdate_enabled: true
update_autoupdate_reboot: false
update_autoupdate_mail_to: ""

# Autoupdate setting on Debian/Ubuntu only
update_autoupdate_reboot_time: "03:00"
update_autoupdate_blacklist: []
update_autoupdate_additional_origins: []

# Autoupdate setting on RedHat only
update_autoupdate_type: "security"
