---
# This task checks the status of a given LXC and sets
# the variable lxc_exist if it is present.
- name: Retrieve LXC status.
  module_defaults:
    community.proxmox.proxmox_vm_info:
      node: "{{ proxmox_node | ansible.builtin.mandatory }}"
      api_host: "{{ proxmox_api_host | ansible.builtin.mandatory }}"
      api_user: "{{ proxmox_api_user | ansible.builtin.mandatory }}"
      vmid: "{{ proxmox_lxc.vmid | ansible.builtin.mandatory }}"
  block:
    - name: Retrieve LXC status via password.
      community.proxmox.proxmox_vm_info: # noqa: args[module]
        api_password: "{{ proxmox_api_password }}"
      register: _proxmox_lxc_status_pwd
      when: "proxmox_is_password_setup"

    - name: Retrieve LXC status via token.
      community.proxmox.proxmox_vm_info: # noqa: args[module]
        api_token_id: "{{ proxmox_api_token_id }}"
        api_token_secret: "{{ proxmox_api_token_secret }}"
      register: _proxmox_lxc_status_token
      when: "proxmox_is_token_setup"

- name: Set '_proxmox_vm_info_result' variable from retrieved state.
  ansible.builtin.set_fact:
    _proxmox_vm_info_result: "{{ (not (_proxmox_lxc_status_token.skipped | default(false))) | ternary(_proxmox_lxc_status_token, _proxmox_lxc_status_pwd) }}"

- name: Fail if the status is not defined.
  ansible.builtin.fail:
    msg: "Error retrieving status of LXC '{{ proxmox_lxc.vmid }}'."
  when: "_proxmox_vm_info_result.proxmox_vms is not defined"

- name: Set 'lxc_exists' variable.
  ansible.builtin.set_fact:
    lxc_exists: "{{ _proxmox_vm_info_result.proxmox_vms | length > 0 | bool }}"
