---
- name: reload systemd # noqa: name[casing]
  ansible.builtin.systemd_service:
    daemon_reload: true
  when: ansible_facts.service_mgr == "systemd"

- name: restart ssh # noqa: name[casing]
  ansible.builtin.service:
    name: "{{ ssh_sshd_name }}"
    state: "restarted"
