---
update_list_upgradable_cmd: "dnf5 list --upgrades -q"

update_automatic_utility: dnf5-plugin-automatic
update_automatic_service: dnf5-automatic.timer
update_automatic_template: automatic.conf.j2
update_automatic_conf_path: /etc/dnf/automatic.conf
