---
update_list_upgradable_cmd: "yum list --upgrades"

update_automatic_utility: yum-cron
update_automatic_service: yum-cron
update_automatic_template: yum-cron.conf.j2
update_automatic_conf_path: /etc/yum/yum-cron.conf
