---
# Reboot the system after updates
system_update_reboot: false

# Check for network connectivity before updating
system_update_network_check: true
system_update_network_dns_domains:
  - "github.com"
system_update_network_http_timeout: 5
system_update_network_http_status_codes:
  - 200
  - 204
system_update_network_http_urls:
  - "https://google.com/generate_204"

# Print upgradable packages
system_update_print_upgradable: true

# Clean old packages
system_update_autoremove: true

# List of additional packages to install
system_update_install_packages: []

# Upgrade type used by APT
system_update_apt_upgrade_type: "safe"

# Configure automatic updates on Debian and RedHat
system_update_autoupdate_enabled: true
system_update_autoupdate_reboot: false
system_update_autoupdate_mail_to: ""

# Autoupdate setting on Debian/Ubuntu only
system_update_autoupdate_reboot_time: "03:00"
system_update_autoupdate_blacklist: []
system_update_autoupdate_additional_origins: []

# Autoupdate setting on RedHat only
system_update_autoupdate_type: "security"
