ansible_user: "root"
# Automatically accept new SSH host keys if they are not present.
# This argument is used sporadically to ensure an high level of security
# without complicating the setup of new hosts.
ansible_ssh_common_args: "-o StrictHostKeyChecking=accept-new"
