---
lxc_appname: "Docker"
proxmox_lxc:
  vmid: 102
  hostname: "docker"
  password: "{{ lxc_default_password }}"
  template:
    name: "debian-12-standard_12.7-1_amd64.tar.zst"
    timeout: 180
  disk_volume:
    storage: "local-lvm"
    size: 4
  cores: 2
  memory: 2048
  netif:
    net0: >-
      name=eth0,ip=192.168.1.122/24,gw={{
        network.gw4
      }},bridge=vmbr0
  features:
    - "keyctl=1"
    - "nesting=1"
  pubkey: "{{ lxc_default_pubkey }}"
  tags:
    - "docker"
  mount_volumes:
    mp0:
      host_path: "/mnt/shared"
      mountpoint: "/srv/shared"
