---
- name: Configure Linux systems.
  hosts: all:!pvenodes
  become: true
  roles:
    - role: roles/system_locale
      when: ansible_facts['distribution'] != 'Alpine'
      tags: locale
    - role: roles/system_update
      tags: update
    - role: roles/system_users
      tags: users
    - role: roles/ssh
      tags: ssh
    - role: roles/motd
      tags: motd
