---
# Inspired by https://github.com/geerlingguy/ansible-role-security/blob/master/tasks/autoupdate-Debian.yml
- name: Install unattended upgrades package.
  ansible.builtin.package:
    name: unattended-upgrades
    state: present

- name: Copy unattended-upgrades configuration files in place.
  ansible.builtin.template:
    src: "{{ __file }}.j2"
    dest: "/etc/apt/apt.conf.d/{{ __file }}"
    owner: "root"
    group: "root"
    mode: "0644"
  loop:
    - 20auto-upgrades
    - 50unattended-upgrades
  loop_control:
    loop_var: __file
